// extension/src/modifiers/bad-status/home-button.tsx
import { o } from "@/stores/options"
import transition, { invalidUrl } from "./transition"

import { Button } from "@/components/ui/button"

export const HomeButton = () => {
  return (
    <Button disabled={invalidUrl} onClick={transition}>
      {o.timeout.timeoutButtonLabel.value}
    </Button>
  )
}

// src/modifiers/bad-status/HomeButton.vue
<script setup lang="ts">
import transition, { invalidUrl } from './transition'
import { o } from "@/stores/options"
</script>

<template lang="pug">
v-btn(color="primary" :disabled="invalidUrl" @click.once="transition")
  | {{ o.timeout.timeoutButtonLabel.value }}
</template>

<style scoped>
</style>
